[package]
name = "sleep"
version = "0.1.0"
authors = ["Keita Takagi <takagi@fluffy.co.jp>"]
edition = "2021"

[dependencies]
winapi = { version = "0.3.9", features = ["powrprof", "processthreadsapi"] }

[build-dependencies]
windres = "0.2.2"

[profile.release]
strip = true
panic = "abort"
